spring.application.name=expense-tracker

jwt.secret-key=dGhpcy1pcy1hLXJlYWxseS1zdHJvbmctYW5kLXNlY3VyZS0zMi1ieXRlLXNlY3JldC1rZXk
jwt.expiration=86400000

spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=${your_password}
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}
